//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARACKİRALAMADBEntities1 : DbContext
    {
        public ARACKİRALAMADBEntities1()
            : base("name=ARACKİRALAMADBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLKİRALIKARAC> TBLKİRALIKARAC { get; set; }
        public virtual DbSet<TBLSATILIKARAC> TBLSATILIKARAC { get; set; }
    }
}
