//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMİN
    {
        public string KULLANİCİAD { get; set; }
        public string SİFRE { get; set; }
        public string PERAD { get; set; }
        public string PERSOYAD { get; set; }
        public string PERYAS { get; set; }
        public string PERCİNSİYET { get; set; }
        public string PERMAAS { get; set; }
        public string PERGÖREV { get; set; }
        public byte PERİD { get; set; }
    }
}
