//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKİRALIKARAC
    {
        public byte ARACID { get; set; }
        public string ARACMARKA { get; set; }
        public string ARACMODEL { get; set; }
        public string ARACRENK { get; set; }
        public string ARACYIL { get; set; }
        public string ARACMUAYENETARİH { get; set; }
        public string ARACTİP { get; set; }
        public string ARACPLAKA { get; set; }
        public string ARACVİTES { get; set; }
        public string ARACFİYAT { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string VERİLİŞTARİH { get; set; }
        public string ALIŞTARİH { get; set; }
        public string MUSTERİADSOYAD { get; set; }
        public string TC { get; set; }
        public string EHLİYETNO { get; set; }
        public string TELNO { get; set; }
        public string ARACRESİM { get; set; }
        public string ODENECEKUCRET { get; set; }
    }
}
